# Generated by Django 2.0.4 on 2018-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('body', models.CharField(max_length=2048)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
